# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-10 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(max_length=255, upload_to='/home/lsteil/Documents/CSVMetadata/')),
                ('title', models.CharField(max_length=255)),
                ('issued', models.DateField()),
                ('publisher', models.CharField(max_length=255)),
                ('contributor', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('data', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=255)),
                ('isPartOf', models.CharField(max_length=255)),
                ('repository', models.CharField(max_length=255)),
                ('rights', models.CharField(max_length=255)),
                ('project_website', models.CharField(max_length=255)),
                ('_format', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'MetaDatas',
                'verbose_name_plural': 'MetaDatas',
                'verbose_name': 'MetaData',
            },
        ),
    ]
