# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-21 23:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIP_generator_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metadata',
            options={'verbose_name': 'MetaData', 'verbose_name_plural': 'MetaDatas'},
        ),
        migrations.AlterModelTable(
            name='metadata',
            table='MetaDatas',
        ),
    ]
