# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-04 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIP_generator_web', '0002_auto_20170621_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='metadata',
            name='creator',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='description',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='formato',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='identifier',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='language',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='publisher',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='relation',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='rights',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='source',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='subject',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='tipo',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metadata',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='contributor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='coverage',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
