# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-05 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIP_generator_web', '0003_auto_20170704_2022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metadata',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='coverage',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='date',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='language',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='relation',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='rights',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='source',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='metadata',
            name='tipo',
        ),
        migrations.AddField(
            model_name='metadata',
            name='repository',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
