# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-06 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIP_generator_web', '0006_auto_20170706_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metadata',
            name='_format',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='contributor',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='description',
            field=models.CharField(default=54564, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='filename',
            field=models.FileField(max_length=255, upload_to=''),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='isPartOf',
            field=models.CharField(default=645654, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='notes',
            field=models.CharField(default=54654654, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='project_website',
            field=models.CharField(default=684654, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='publisher',
            field=models.CharField(default=64564, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='repository',
            field=models.CharField(default=45654, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='rights',
            field=models.CharField(default=684654, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='subject',
            field=models.CharField(default=46546, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='title',
            field=models.CharField(default=654654, max_length=255),
            preserve_default=False,
        ),
    ]
